// SPDX-License-Identifier: MIT
pragma solidity ^0.6.12;


import '@openzeppelin/contracts/access/Ownable.sol';
import "@openzeppelin/contracts/utils/Counters.sol";
import '@openzeppelin/contracts/math/SafeMath.sol';
import '@openzeppelin/contracts/payment/escrow/RefundEscrow.sol';
import './Pact.sol';


contract BetterTogetherGateway is Ownable {

    // Use SafeMath because its safe
    using SafeMath for uint256;
    // Use counter to track all ids
    using Counters for Counters.Counter;

    // Track the pacts we have
    Pact[] public pacts;
    Counters.Counter private _numOfPacts;
    // Track the originator to their escrow
    mapping (address => uint256) private _originatorToEscrowIndex;
    // Achieve 1 goal at a time
    mapping (address => bool) private _host;

    //@dev Wallet to hold all the money for these pacts
    //We try our best to make sure that no one can withdraw more than they put in
    //This is probably cheaper than deploying an actual contract
    address payable wallet;

    // @dev borrowed from
    // https://medium.com/@ethdapp/using-the-openzeppelin-escrow-library-6384f22caa99
    constructor(address payable _wallet) public {
        wallet = _wallet;
    }
    
    // @dev helper function to just get the contract index and make sure that it exists
    // All contracts will start at >= 1
    function _getPact(address a) internal view returns (Pact) {
        uint256 contractIndex = _originatorToEscrowIndex[a];
        require(contractIndex > 0, "Your friend doesn't want to be better together");
        return pacts[contractIndex];
    }

    function _compareStringsByBytes(string memory s1, string memory s2) internal pure returns(bool){
        return keccak256(abi.encodePacked(s1)) == keccak256(abi.encodePacked(s2));
    }
    
    // @dev We take the msg.sender and create a goal for them
    // Check to make sure they are not currently an originator for being better together movement
    // If they are not hosting we return the invite code for their goal
    function weAreBetterTogether() external returns (string memory) {
        require(_originatorToEscrowIndex[msg.sender] == 0, "You already have a pact!");
        _numOfPacts.increment();
        Pact pact = new Pact(wallet, msg.sender, _numOfPacts.current());
        pacts.push(pact);
        _originatorToEscrowIndex[msg.sender] = pact.id();
        return pact.inviteCode();
    }

    // @dev gets sender's contract invite (generated by VRF) embedded into goal
    function getInviteCode() external view returns (string memory) {
        Pact pact = _getPact(msg.sender);
        return pact.inviteCode();
    }

    // @dev given an invite code register the sender to that contract
    function beBetterTogether(string memory invite, address referrer) external {
        Pact pact = _getPact(referrer);
        require(!_compareStringsByBytes(pact.inviteCode(), invite), "You're friend gave you the wrong invite!");
        // Register the address to that escrow too here and in the contract
        _originatorToEscrowIndex[msg.sender] = pact.id();
        // Add the address to pact
        pact.addParticipant(msg.sender);
    }

    // TODO check the progress
    function getProgress() public view returns (bool) {
        return true;
    }
}
