// SPDX-License-Identifier: MIT
pragma solidity ^0.6.12;


import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Counters.sol";
import "@openzeppelin/contracts/math/SafeMath.sol";
import "@openzeppelin/contracts/payment/escrow/RefundEscrow.sol";
import "./Pact.sol";
import "./stravaClient/IStravaClient.sol";
import "./inviteCodeClient/IInviteCodeClient.sol";
import "./alarmClient/IAlarmClient.sol";


contract BetterTogetherGateway is Ownable {

    // Use SafeMath because its safe
    using SafeMath for uint256;
    // Use counter to track all ids
    using Counters for Counters.Counter;

    // Events to listen to if we so choose to
    event PactCreated(address _host, uint256 _id);

    // Track the pacts we have
    Pact[] public pacts;
    Counters.Counter private _numOfPacts;
    // Track the originator to their escrow
    mapping (address => uint256) private _originatorToEscrowIndex;
    // Achieve 1 goal at a time
    mapping (address => bool) private _host;

    // @dev Wallet to hold all the money for these pacts
    // This is probably cheaper than deploying an actual contract
    address payable wallet;

    // Client's that we'll inject into our Pact
    IStravaClient stravaClient;
    IInviteCodeClient inviteCodeClient;
    IAlarmClient alarmClient;

    // @dev borrowed from
    // https://medium.com/@ethdapp/using-the-openzeppelin-escrow-library-6384f22caa99
    constructor(address payable _wallet) public {
        wallet = _wallet;
        // We want all new contracts from this gateway to start at 1
        Pact dummy = new Pact(wallet, msg.sender, _numOfPacts.current());
        pacts.push(dummy);
        _numOfPacts.increment();
    }
    
    // @dev helper function to just get the contract index and make sure that it exists
    // All contracts will start at >= 1
    // TODO This will probably go away and just be inside getMyPact
    function _getPact(address a) internal view returns (Pact) {
        uint256 contractIndex = _originatorToEscrowIndex[a];
        require(contractIndex > 0, "Your friend doesn't want to be better together");
        return pacts[contractIndex];
    }
    
    // @dev We take the msg.sender and create a goal for them
    // Check to make sure they are not currently an originator for being better together movement
    // If they are not hosting we return the invite code for their goal
    function weAreBetterTogether() external {
        require(_originatorToEscrowIndex[msg.sender] == 0, "You already have a pact!");
        Pact pact = new Pact(wallet, msg.sender, _numOfPacts.current());
        pacts.push(pact);
        // We track w/ gateway just in case the host forgets their Pact address
        _originatorToEscrowIndex[msg.sender] = _numOfPacts.current();
        _numOfPacts.increment();
        emit PactCreated(msg.sender, pact.id());
    }

    // @dev Return the Pact Address after we've created pact
    function getMyPact() external view returns (address) {
        Pact pact = _getPact(msg.sender);
        return address(pact);
    }

    // @dev gets sender's contract invite (generated by VRF) embedded into goal
    // TODO Just move this into the Pact Contract
    function getInviteCode() external view returns (string memory) {
        Pact pact = _getPact(msg.sender);
        return pact.inviteCode();
    }

    // This is just to debug stuff
    // If we invoke a method on pact, and we try to use msg.sender inside that method
    // The msg.sender is not the person who c alled this method from the gateway
    // The msg.sender pact.foo sees is the owner of this contract
    // Therefore in any method where you want the msg.sender for gateway to be passed
    // to the pact's method, we probably have to pass it in through a param
    // TODO is there anyway to bind it? I guess not because this would cost gas on behalf of the requester?
    // Maybe we should just return the address from gateway and have the owner call that contract
    function foo() public view returns (address, address, address) {
        Pact pact = _getPact(msg.sender);
        return pact.foo(msg.sender);
    }
}
